### ISSUE TITLE
two way sync in sync manager!

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-flutter#388]
it'll only sync the notes that already exist in Fleeting Notes. It won't pull new notes that aren't on the device locally! It'll only pull new notes from the supabase database. and sync those with the new device.,

It makes sense because, we don't want to make massive requests to external databases / APIs from within the application. Also, we don't want other people to exclusively use other syncing options. We want them to go through Fleeting Notes!

**Comment by stanleyguevara** [comment]
Hey @matthewwong525, is this still intended behaviour?

> it'll only sync the notes that already exist in Fleeting Notes

If so, then I think it'll be nice to document it a bit better in the notes user gets on startup.
I've spent quite a bit of time creating new notes on desktop, putting them into FleetingNotesApp folder and wondering why those are not synced to android / web.

If user sees "Two way sync" it's quite reasonable to think it'll sync the whole folder, both ways.

Nice app BTW!

**Comment by matthewwong525** [comment]
Good point on the documentation, I'll look into a way to add it in there. That currently is the intended behaviour for now but there is a ticket to add this additional feature. If that's something you'd like, definitely go and give it a thumbs up here.

https://github.com/fleetingnotes/fleeting-notes-obsidian/issues/65
