### ISSUE TITLE
Filename inaccurate in Android w Obsidian Sync

### ISSUE THREAD

**Issue by 2Hedz** [fleetingnotes/fleeting-notes-flutter#488]
**Describe your bug**
Trouble with the filename saving. It seemed to only start to occur after I enabled Obsidian sync (running Android 11). The sync is immediate since I have the Obsidian vault pointing to the same as the Fleeting Notes output folder. A new local note in FN is saved almost immediately...even before I can write the full title. So the filename becomes some long alphanumeric jumble (like 61259770-a01e-11ed...etc) instead of the correct name (i.e. the title). I noticed this also @0:19 in your YT video "The best browser extension for Obsidian". In your 'test' folder in Obsidian you show a file named db16eb20-0f86...etc. Not sure if it is the same bug but maybe.A clear and concise description of what the bug is.

**To Reproduce**
1. Go to FN, start new note
2. File immediately created with incorrect name
3. File must be renamed in Obsidian manually 

**Expected behavior**
Filename saved as random alphanumeric ex.  61259770-a01e-11ed...etc...md

**Screenshots**

**Extra Info (please complete the following information):**
 - Device: Samsung GalaxyTab S7+
 - OS / Browser: Android 13
 - Fleeting Notes Version v0.7.6

**Suggestion**
Perhaps a fix would be making it so the 1st save operation only happens after the note is _initially_ completed (only after back arrow is tapped for the 1st time).  On subsequent openings of the note the high frequency save operations can happen. 

That would be more elegant than needing an additional renaming operation in my opinion.

Cheers.

**Comment by matthewwong525** [comment]
thank you for such a detailed issue! I like your suggestion and I will most likely find a way to implement something like this!

**Comment by matthewwong525** [comment]
#559
