### ISSUE TITLE
Feature Request: Ability to change the size of the pop-up

### ISSUE THREAD

**Issue by spiritualgeek** [fleetingnotes/fleeting-notes-flutter#497]
**Is your feature request related to a problem? Please describe.**
The pop-up is tiny on a display with a high resolution.

**Describe the solution you'd like**
Would it be possible to set the size of the pop-up? - At least be able to drag it to be larger?

**Describe alternatives you've considered**
If there was an alternative, I would consider it

**Additional context**
N/A

**Comment by matthewwong525** [comment]
Look into wrapping a div and detecting the onhover event
https://stackoverflow.com/a/1571158/13659833

OR use offsets:
https://stackoverflow.com/a/36622185/13659833

Then save the result locally and load use it to set the width on initialize everytime.

**Comment by matthewwong525** [comment]
@spiritualgeek made a PR for this. If you're curious as to what it looks like, checkout this tweet: https://twitter.com/fleetingnotes_/status/1623770544842723332?s=20&t=Rc22JhYAsp0heDM5PhyjkA

**Comment by spiritualgeek** [comment]
Looks brilliant!

Thanks so much

When will it be released?

**Comment by matthewwong525** [comment]
In a couple of days! depends on review time
