### ISSUE TITLE
Feature request: Frictionless adding of attachments

### ISSUE THREAD

**Issue by spiritualgeek** [fleetingnotes/fleeting-notes-flutter#498]
**Is your feature request related to a problem? Please describe.**
You should not have to save an image to disk and then chose "Add attachment".

**Describe the solution you'd like**
You should be able to drag the image into the note or at most drag it to yoink (Mac user here) and then into the note. 

**Describe alternatives you've considered**
If there is an alternative and keen to hear what it is

**Additional context**
The same would apply to other files, but images in particular

**Comment by spiritualgeek** [comment]
Not using fleeting notes anymore

**Comment by matthewwong525** [comment]
@spiritualgeek would love to understand how I could make Fleeting Notes better for you! Going to keep this open because I still want to work on it.

**Comment by spiritualgeek** [comment]
> @spiritualgeek would love to understand how I could make Fleeting Notes better for you! Going to keep this open because I still want to work on it.

I was paying monthly and using too infrequently. When your price became $6/month, I just decided that Readwise Reader would be better suited to me and signed onto them for a year ($96 for the year)

I wish you well in your endeavour

**Comment by matthewwong525** [comment]
> > @spiritualgeek would love to understand how I could make Fleeting Notes better for you! Going to keep this open because I still want to work on it.
> 
> I was paying monthly and using too infrequently. When your price became $6/month, I just decided that Readwise Reader would be better suited to me and signed onto them for a year ($96 for the year)
> 
> I wish you well in your endeavour

Hello, if you are previously subscribed you will maintain your grandfathered rate. But thank you for your well wishes. I appreciate the feedback, as always
