### ISSUE TITLE
Deleted Fleeting Notes Reappear

### ISSUE THREAD

**Issue by papadage** [fleetingnotes/fleeting-notes-flutter#513]
**Deleted Fleeting Notes Reappear in Obsidian** 
I have no fleeting notes visible in the iOS app and Chrome extension, When I delete some of the hints nlotes that were created when installing the community plug-in in Obsidian, they reappear several minutes later despite them not being in the app or extension. This happens whether I delete them in the app, or if I do so directly in the Windows file system.

**To Reproduce**
1. Verify that the iOS app and Chrome extension shgow no notes
2. Open the Fleeting Notes target folder in Obsidian
3. Delete the hint notes
4. Wait a half hour or so

**Expected behavior**
Notes that are deleted should not reappear if they do not exist or are not visible in the app. 

**Screenshots**
This is on Windows, on my desktop, but it is the same on my laptop and iPad Pro

![image](https://user-images.githubusercontent.com/28878971/219511702-1f310a74-5a62-4945-9bda-a672687dd7fc.png)

**Extra Info (please complete the following information):**
 - Device: All devices (Windows 11 Desktop, Windows 10 laptop, M1 iPad Pro 12.9, iPhone 12 Pro Max)
 - OS / Browser: Windows 11, Windows 10, iOS
 - Fleeting Notes Version: 0.5.2

**Comment by matthewwong525** [comment]
Thanks for putting this together! It's very helpful 🙂

**Comment by matthewwong525** [comment]
@papadage can you verify that this is still the behaviour? This should be fixed as of https://github.com/fleetingnotes/fleeting-notes-obsidian/issues/75 . I will close this issue but if you do encounter the problem feel free to reopen it :)
