### ISSUE TITLE
Highlight from same page

### ISSUE THREAD

**Issue by Christianvala** [fleetingnotes/fleeting-notes-flutter#550]
**Is your feature request related to a problem? Please describe.**
1. Highlights from same page goes into different notes.
2. You have to double click or right click to find the fleeting notes feature.

**Describe the solution you'd like**
1. Would be nice if you could choose, to have highlights from the same page go into the same note.
2. Would be nice if fleeting notes just popped up as you covered the text.

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewwong525** [comment]
Hey Christian!

I've recently added a toggle to enable this. it'll be released in the next release. Check it out below:

let me know if this helps

https://github.com/fleetingnotes/fleeting-notes-flutter/issues/462

**Comment by matthewwong525** [comment]
I'm going to close this ticket, feel free to reopen it if this doesn't solve your problem!
