### ISSUE TITLE
Display version number

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-flutter#621]
**Is your feature request related to a problem? Please describe.**
Desktop apps of FN doesn't auto update so better to display version #

**Describe the solution you'd like**
Display version number at the bottom / top of the drawer or in settings

**Comment by musicleaf** [comment]
最好是在官网上的下载页面上,也显示最新的MacOS上显示最新的版本号, 对比版本号,确定是否下载

**Comment by matthewwong525** [comment]
> 最好是在官网上的下载页面上,也显示最新的MacOS上显示最新的版本号, 对比版本号,确定是否下载.
> 
> 当然也可以在设置页面显示 当前的版本和最新的版本号, 然后可以官网下载

translation: "It would be best if the latest version number is also displayed on the download page of the official website for MacOS, to compare the version numbers and determine whether to download.

Of course, you can also display the current version and the latest version number on the settings page, and then download from the official website."
