### ISSUE TITLE
Have a trash bin to see deleted notes

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-flutter#668]
**Is your feature request related to a problem? Please describe.**
Some people would like to see deleted notes

**Describe the solution you'd like**
- i want another button on top of the settings button "Trash". 
![Image](https://github.com/fleetingnotes/fleeting-notes-flutter/assets/20890995/5bb71cc4-20e8-47ed-b62a-c2391805eb1a)
- show the same settings screen, at the top there will be a [banner](https://api.flutter.dev/flutter/material/MaterialBanner-class.html) that says "Deleted Notes" and a "Go Back" button which will bring them back to the normal settings screen
- so when they click on the deleted note it'll open a dialog which will ask if they want to restore the note, with two buttons "Restore" and "Cancel"
- remove bottom bar to add note and stuff

**Additional context**
- at least 2 people asked for this.

**Comment by gonzalovelasco** [comment]
Closes by https://github.com/fleetingnotes/fleeting-notes-flutter/pull/841
