### ISSUE TITLE
Remove wiredash

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-flutter#689]
**Is your feature request related to a problem? Please describe.**
- Wiredash is nice but it's not that great because no one really uses the features also sometimes the email field is not always populated
- Also replying isn't that great because it might hit their spam
- 

**Describe the solution you'd like**
- I want the feedback button to directly open the default email app and prepopulate in the formate below, for example:
```
Title: `Fleeting Notes Feedback`
Subject: `(Device: iOS, Version: 0.10.4)\n`
```
- use [url_launcher](https://pub.dev/packages/url_launcher#:~:text=the%20default%20browser-,mailto,-%3A%3Cemail%20address%3E%3Fsubject) package

**Comment by gonzalovelasco** [comment]
Closes https://github.com/fleetingnotes/fleeting-notes-flutter/pull/695

**Comment by gonzalovelasco** [comment]
Closes https://github.com/fleetingnotes/fleeting-notes-flutter/pull/695
