### ISSUE TITLE
MAC端，希望有快捷键快速返回首页，比如esc键

### ISSUE THREAD

**Issue by musicleaf** [fleetingnotes/fleeting-notes-flutter#746]
现在每次都要点击左上角的 X， 效率不够高

<img width="507" alt="image" src="https://github.com/fleetingnotes/fleeting-notes-flutter/assets/35360006/186306e0-6759-481a-9830-d87067d56520">

On the MAC side, hoping for a shortcut key to quickly return to the homepage, like the esc key.

**Comment by matthewwong525** [comment]
Related to #763
