### ISSUE TITLE
not connected to ios / android password manager

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-flutter#893]
**Is your feature request related to a problem? Please describe.**
Not able to use password manager when logging in / signing up easily on iOS

**Describe the solution you'd like**
When logging in, iphone able to detect pw manager

**Comment by matthewwong525** [comment]
i think this i just the matter of like wrapping everything in a form? or like adding an email attribute to the textfieldz

**Comment by legolasdimir** [comment]
Pretty sure that the app needs to support the Android autofill API
